# Generated by Django 6.0.4 on 2026-04-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='date',
        ),
        migrations.AddField(
            model_name='document',
            name='page',
            field=models.CharField(default='sixieme', max_length=100),
        ),
    ]
